<?php

/**
 * BaseOurTeam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $employee_id
 * @property string $employee_name
 * @property string $employee_designation
 * @property string $employee_img
 * @property string $employee_bio
 * 
 * @method string  getEmployeeId()           Returns the current record's "employee_id" value
 * @method string  getEmployeeName()         Returns the current record's "employee_name" value
 * @method string  getEmployeeDesignation()  Returns the current record's "employee_designation" value
 * @method string  getEmployeeImg()          Returns the current record's "employee_img" value
 * @method string  getEmployeeBio()          Returns the current record's "employee_bio" value
 * @method OurTeam setEmployeeId()           Sets the current record's "employee_id" value
 * @method OurTeam setEmployeeName()         Sets the current record's "employee_name" value
 * @method OurTeam setEmployeeDesignation()  Sets the current record's "employee_designation" value
 * @method OurTeam setEmployeeImg()          Sets the current record's "employee_img" value
 * @method OurTeam setEmployeeBio()          Sets the current record's "employee_bio" value
 * 
 * @package    sitetwintog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOurTeam extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('our_team');
        $this->hasColumn('employee_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('employee_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('employee_designation', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('employee_img', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('employee_bio', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}