<?php

/**
 * BaseUserDetails
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $email_address
 * @property string $message
 * 
 * @method string      getName()          Returns the current record's "name" value
 * @method string      getEmailAddress()  Returns the current record's "email_address" value
 * @method string      getMessage()       Returns the current record's "message" value
 * @method UserDetails setName()          Sets the current record's "name" value
 * @method UserDetails setEmailAddress()  Sets the current record's "email_address" value
 * @method UserDetails setMessage()       Sets the current record's "message" value
 * 
 * @package    sitetwintog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserDetails extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_details');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('email_address', 'string', 255, array(
             'type' => 'string',
             'notblank' => true,
             'email' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('message', 'string', 5000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 5000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}