<?php

/**
 * BaseGallery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $image_title
 * @property string $image_url
 * 
 * @method string  getImageTitle()  Returns the current record's "image_title" value
 * @method string  getImageUrl()    Returns the current record's "image_url" value
 * @method Gallery setImageTitle()  Sets the current record's "image_title" value
 * @method Gallery setImageUrl()    Sets the current record's "image_url" value
 * 
 * @package    sitetwintog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGallery extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gallery');
        $this->hasColumn('image_title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('image_url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}