<?php

/**
 * BaseStaticContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $about_us
 * @property string $about_us_img
 * @property string $services_web
 * @property string $services_seo
 * @property string $services_app
 * 
 * @method string        getAboutUs()      Returns the current record's "about_us" value
 * @method string        getAboutUsImg()   Returns the current record's "about_us_img" value
 * @method string        getServicesWeb()  Returns the current record's "services_web" value
 * @method string        getServicesSeo()  Returns the current record's "services_seo" value
 * @method string        getServicesApp()  Returns the current record's "services_app" value
 * @method StaticContent setAboutUs()      Sets the current record's "about_us" value
 * @method StaticContent setAboutUsImg()   Sets the current record's "about_us_img" value
 * @method StaticContent setServicesWeb()  Sets the current record's "services_web" value
 * @method StaticContent setServicesSeo()  Sets the current record's "services_seo" value
 * @method StaticContent setServicesApp()  Sets the current record's "services_app" value
 * 
 * @package    sitetwintog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStaticContent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('static_content');
        $this->hasColumn('about_us', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             ));
        $this->hasColumn('about_us_img', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('services_web', 'string', 5000, array(
             'type' => 'string',
             'length' => 5000,
             ));
        $this->hasColumn('services_seo', 'string', 5000, array(
             'type' => 'string',
             'length' => 5000,
             ));
        $this->hasColumn('services_app', 'string', 5000, array(
             'type' => 'string',
             'length' => 5000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}