# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, redmond/jquery-ui-1.8.5.custom.css, jquery/jquery.autocompleter.css, jquery.multiselect.css, layout-admin.css]

  javascripts:    [jquery.min.js,bootstrap.min.js,jquery.flexslider.js,jquery.singlePageNav.js,modernizr.js,templatemo_custom.js]

  has_layout:     true
  layout:         layout
