<?php

/**
 * OurTeamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OurTeamTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OurTeamTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OurTeam');
    }
}