<?php

/**
 * StaticContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StaticContentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StaticContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StaticContent');
    }
}