generator:
  class: sfDoctrineGenerator
  param:
    model_class:           StaticContent
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          static_content
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [about_us_img,created_at]
        max_per_page:   10
        batch_actions: {}
        object_actions:
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
