<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('static_content', 'about_us_img_content', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('static_content', 'about_us_img_content');
    }
}