generator:
  class: sfDoctrineGenerator
  param:
    model_class:           UserDetails
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          user_details
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [name, email_address,created_at]
        max_per_page:   10
        batch_actions: {}
        object_actions:        
          _edit:      ~
          _delete:    ~
        actions:
          _export: ~          
      filter:  ~
      form:
        actions:
          _list: ~
          _save:
      edit:    ~
      new:     ~
